"""empty message

Revision ID: 4a3fc184dc97
Revises: b4401186d7ad
Create Date: 2024-04-11 19:08:08.518223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3fc184dc97'
down_revision = 'b4401186d7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar image', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.Unicode(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar image', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Unicode(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
